---

- hosts: all
  become: true
  tasks: 

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == ["Debian", "Ubuntu"]

  - name: upgrade repository index
    apt:
      upgrade: dist
    when: ansible_distribution == "Ubuntu"

  - name: install apache2 package
    apt: 
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install docker package
    apt:
      name: docker
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install docker-compose package
    apt:
      name: docker-compose
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install python3
    apt:
      name: python3
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install python3-pip
    apt:
      name: python3-pip
      state: latest
    when: ansible_distribution == "Ubuntu"

