---

- hosts: all
  become: true
  pre_tasks: 

  - name: update & upgrade repository index
    register: updatesys
    apt:
      update_cache: yes
      upgrade: dist
      cache_valid_time: 3600

  - name: Display the last line of the previous task to check stats
    debug:
      msg: "{{updatesys.stdout_lines|last}}"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 & libapache2-mod-php packages
    apt: 
      name:
        - apache2
        - libapache2-mod-php
      state: latest


- hosts:
    - media_servers
    - web_servers
  become: true
  tasks:

  - name: install packages for mediaservers
    apt:
      name:
        - docker
        - docker-compose
        - python3
        - python3-pip
      state: latest
