---
- name: play
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: clone git repo
      git:
        repo: "https://github.com/dannmandb/ansible.git"
        dest: "{{ lookup('env', 'HOME') }}/ansible"
        version: main
