---

- hosts: test_servers
  become: true
  tasks: 

  - name: update repository index
    apt:
      update_cache: yes

  - name: upgrade repository index
    apt:
      upgrade: dist

  - name: remove apache2 package
    apt: 
      name: apache2
      state: absent

  - name: install docker package
    apt:
      name: docker
      state: absent

  - name: install docker-compose package
    apt:
      name: docker-compose
      state: absent

  - name: install php support for apache
    apt:
      name: libapache2-mod-php
      state: absent

  - name: install python3
    apt:
      name: python3
      state: latest

  - name: install python3-pip
    apt:
      name: python3-pip
      state: latest

