---

- hosts: test_servers
  become: true
  pre_tasks: 

  - name: update & upgrade repository index
    register: updatesys
    apt:
      update_cache: yes
      upgrade: dist
      cache_valid_time: 3600

  - name: Display the last line of the previous task to check stats
    debug:
      msg: "{{updatesys.stdout_lines|last}}"

- hosts: test_servers
  become: true
  tasks:
  - name: Creates directory
    file:
      path: "{{ item }}"
      state: directory
      owner: daniel
      group: daniel
      mode: 0775
      recurse: yes
    with_items:
      - /opt/appdata/docker/sys/test
      - /opt/appdata/docker/lab/test
