- name: Add the user 'daniel' with a specific uid and a primary group of 'admin'
  ansible.builtin.user:
    name: daniel
    comment: Dann Man db
    uid: 1040
    group: admin
- name: Create a 2048-bit SSH key for user daniel in ~daniel/.ssh/id_rsa
  ansible.builtin.user:
    name: daniel
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
