version: "3.3"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data

  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    volumes:
      - /opt/appdata/gluetun/config:/data/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=private internet access
      - OPENVPN_USER=p0790330
      - OPENVPN_PASSWORD=Sba27p23er
      - SERVER_REGIONS=Netherlands

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/appdata/sabnzbd/config:/data/config
 #     - /media/usb/11TB:/data-11TB #optional
  #    - /media/usb/6TB-A:/data-6TB-A
      - ~/Downloads/incomplete:/downloads
    ports:
      - 8081:8080
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/appdata/radarr/config:/data/config
   #   - /media/usb/11TB:/data-11TB #optional
    #  - /media/usb/6TB-A:/data-6TB-A #optional
      - ~/Downloads/incomplete:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/appdata/sonarr/config:/data/config
#      - /media/usb/11TB:/data-11TB #optional
 #     - /media/usb/6TB-A:/data-6TB-A #optional
      - ~/Downloads/incomplete:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: lidarr
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /opt/appdata/lidarr/config:/data/config
 #     - /media/usb/11TB:/data-11TB #optional
  #    - /media/usb/6TB-A:/data-6TB-A #optional
      - ~/Downloads/incomplete:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

  ombi:
    image: lscr.io/linuxserver/ombi:latest
    container_name: ombi
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - BASE_URL=/ombi #optional
    volumes:
      - /opt/appdata/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - /opt/appdata/qtorrent/config:/config
  #    - /media/usb/11TB/downloads:/downloads
      - ~/Downloads/incomplete:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    depends_on:
      - gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /opt/appdata/jackett/config:/config
#      - /media/usb/11TB/downloads:/downloads
      - ~/Downloads/incomplete:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - ./homarr/configs:/app/data/configs
      - ./homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - '7575:7575'

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= claim-Jby6mh-kYe4ig2ZvVoJE #optional
    volumes:
      - /opt/appdata/plex/library:/config
      - /opt/appdata/plex/media/tvseries:/tv
      - /opt/appdata/plex/media/movies:/movies
      - /opt/appdata/plex/media/music:/music
      - ~/Downloads:/downloads
    restart: unless-stopped

  yacht:
    container_name: yacht
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - yacht:/config
      - /var/run/docker.sock:/var/run/docker.sock
    image: selfhostedpro/yacht

  nginxproxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  db:
    driver: local
  cache:
    driver: local
  yacht:
  